name: CI/CD for Hello World HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Start Local Server
        run: |
          python -m http.server 8000 &
          sleep 5
          curl -I http://localhost:8000/index.html

      - name: Deploy
        run: echo "Deployed locally on http://localhost:8000"
